I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mods.rpy", line 1, in script
    init -1 python:
  File "game/mods.rpy", line 21, in <module>
    if persistent.mod[namemod] is '0':
TypeError: 'NoneType' object has no attribute '__getitem__'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Carion\Desktop\Renpy\renpy\bootstrap.py", line 288, in bootstrap
    renpy.main.main()
  File "C:\Users\Carion\Desktop\Renpy\renpy\main.py", line 321, in main
    game.context().run(node)
  File "game/mods.rpy", line 1, in script
    init -1 python:
  File "C:\Users\Carion\Desktop\Renpy\renpy\ast.py", line 785, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Carion\Desktop\Renpy\renpy\python.py", line 1445, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/mods.rpy", line 21, in <module>
    if persistent.mod[namemod] is '0':
TypeError: 'NoneType' object has no attribute '__getitem__'

Windows-8-6.2.9200
Ren'Py 6.99.3.404
 
